export const initialValues = {
  name: "",
  price: "",
  cartype_id: "",
//   route_id: "",
  seat: "",
  date_active: "",
  start_time: "",
  description: "",
  startPointName: "",
  startPointId: "",
  endPointName: "",
  endPointId: "",
  service_id: [],
};
